//! Build-time code generation.
//!
//! 1. Generate `$OUT_DIR/cert_hash.rs` with the expected APK signing cert
//!    SHA-256. Source is the `OPENMONITOR_CERT_SHA256` env var, a 64-char
//!    lowercase hex string populated by the Gradle `computeCertSha256` task
//!    (see `app/build.gradle.kts` — Phase A3).
//!
//!    If the env var is absent (plain `cargo check` on a laptop with no
//!    Gradle in the loop), we emit 32 zero bytes. That sentinel is caught by
//!    `AuthConfig::is_sentinel()` and the auth layer refuses every peer —
//!    the safe default.
//!
//! 2. On Android targets, emit the usual `rustc-link-lib` hints.

use std::io::Write;

fn main() {
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os == "android" {
        // Kept for future use (e.g. if we re-link ASharedMemory_create);
        // harmless if unused.
        println!("cargo:rustc-link-lib=android");
    }

    generate_cert_hash();

    println!("cargo:rerun-if-env-changed=OPENMONITOR_CERT_SHA256");
    println!("cargo:rerun-if-changed=build.rs");
}

fn generate_cert_hash() {
    let bytes = match std::env::var("OPENMONITOR_CERT_SHA256") {
        Ok(hex) => parse_sha256_hex(&hex)
            .unwrap_or_else(|e| panic!("OPENMONITOR_CERT_SHA256 invalid: {e}")),
        Err(_) => [0u8; 32],
    };

    let out_dir = std::env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let out_path = std::path::Path::new(&out_dir).join("cert_hash.rs");
    let mut f = std::fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));

    writeln!(f, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(f, "pub const EXPECTED_CERT_SHA256: [u8; 32] = [").unwrap();
    for chunk in bytes.chunks(8) {
        write!(f, "    ").unwrap();
        for b in chunk {
            write!(f, "0x{:02x}, ", b).unwrap();
        }
        writeln!(f).unwrap();
    }
    writeln!(f, "];").unwrap();
}

fn parse_sha256_hex(hex: &str) -> Result<[u8; 32], String> {
    let hex = hex.trim();
    if hex.len() != 64 {
        return Err(format!("expected 64 hex chars, got {}", hex.len()));
    }
    let mut out = [0u8; 32];
    for i in 0..32 {
        let byte = &hex[i * 2..i * 2 + 2];
        out[i] = u8::from_str_radix(byte, 16)
            .map_err(|_| format!("non-hex byte at position {}: {byte}", i * 2))?;
    }
    Ok(out)
}
